export const products = [
  {
    id: 1,
    url: require("@/assets/images/Firetrap/FireTrap1.jpeg"),
    name: "Firetrap Hoodie",
    price: 20,

    quantity: 59,
    category: "Hoodies",
    description: "Transitory neonatal hyperthyroidism",
  },
  {
    id: 2,
    url: require("@/assets/images/Firetrap/FireTrap2.jpeg"),
    name: "Firetrap Jeans",
    price: 19,

    quantity: 59,
    category: "Jeans",
    description: "Transitory neonatal hyperthyroidism",
  },
  {
    id: 3,
    url: require("@/assets/images/Firetrap/FireTrap3.jpeg"),
    name: "Firetrap T-shirt",
    price: 15,
    quantity: 59,
    category: "T-shirts",
    description: "Transitory neonatal hyperthyroidism",
  },
  {
    id: 4,
    url: require("@/assets/images/Gucci/gucci1.jpeg"),
    name: "Gucci Mushroom Jumper",
    price: 29,
    quantity: 6,
    category: "Construction Clean and Final Clean",
    description: "Disp fx of greater tuberosity of unsp humer, 7thK",
  },
  {
    id: 5,
    url: require("@/assets/images/Gucci/gucci2.jpeg"),
    name: "Gucci Black & White T-shirt",
    price: 20,
    quantity: 59,
    category: "T-shirts",
    description: "Transitory neonatal hyperthyroidism",
  },
  {
    id: 6,
    url: require("@/assets/images/Gucci/gucci3.jpeg"),
    name: "Gucci Red & White T-shirt",
    price: 17,
    quantity: 21,
    category: "T-shirts",
    description: "Chronic gout due to renal impairment, knee",
  },
  {
    id: 7,
    url: require("@/assets/images/Nike/Nike1.jpeg"),
    name: "Nike Top & Tracksuit",
    price: 23,
    quantity: 55,
    category: "Tracksuit",
    description: "Displaced associated transv/post fx right acetab, sequela",
  },
  {
    id: 8,
    url: require("@/assets/images/Nike/Nike2.jpeg"),
    name: "Nike Cardigan",
    price: 19,
    quantity: 60,
    category: "Cardigan",
    description: "Follicular lymphoma grade III, unsp, intrathorac lymph nodes",
  },
  {
    id: 9,
    url: require("@/assets/images/Nike/Nike3.jpeg"),
    name: "Nike shorts",
    price: 15,
    quantity: 90,
    category: "Shorts",
    description: "Toxic effect of other alcohols, intentional self-harm",
  },
  {
    id: 10,
    url: require("@/assets/images/Sketchers/sketchers1.jpeg"),
    name: "Sketcher blue shoe",
    price: 20,
    quantity: 4,
    category: "Shoes",
    description: "Schizoaffective disorder, unspecified",
  },
  {
    id: 11,
    url: require("@/assets/images/Sketchers/sketchers2.jpeg"),
    name: "Sketcher blue sandal",
    price: 14,
    quantity: 31,
    category: "Shoes",
    description: "Athscl unsp type bypass of the extrm w gangrene, oth extrm",
  },
];

export const CATEGORIES = [
  "Cardigan",
  "T-shirts",
  "Jackets",
  "Shirts",
  "Hoodies",
  "Jumpers",
  "Trousers",
  "Tracksuit",
  "Jeans",
  "Joggers",
  "Vests",
  "Sweatshirts",
  "Socks",
  "Shorts",
  "Shoes"
];

[];
